name: compile-lists

on:
  # manual
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*
      - config/*
      - build.sh
  schedule:
    - cron: "51 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: compile lists
        id: compile-lists
        run: |
          ./build.sh
          echo "date=$(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT
      - name: Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Filter List
          body: |
            Latest compiled filter list
            Updated: ${{ steps.compile-lists.outputs.date }}
          files: compiled/hostlist.txt
          make_latest: true
